import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Aside from "@/components/Aside";
import Main from "@/components/Main";
import Menu from "@/components/Menu";

import { Providers } from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex relative">
          <Providers>
            <Aside />
            <Menu />
            <Main>{children}</Main>
          </Providers>
        </main>
      </body>
    </html>
  );
}
